### ISSUE TITLE
500 hotglue-bundle-1.js breaking client-side javascript

### ISSUE THREAD

**Issue by kanaabe** [artsy/team-navigator#100]
It looks like since [this commit](https://github.com/artsy/team-navigator/pull/99/commits/29921b576b72f8b310687da05e5835429bc9adbf) we're no longer getting client-side js working. I haven't dug into the details but the server-side error we kept seeing: `Error: Cannot find module './lib-cov'` is also related to this.

**Comment by orta** [comment]
Full log:

![screen shot 2017-08-21 at 16 42 28](https://user-images.githubusercontent.com/49038/29537472-dfc5ae2a-868f-11e7-962b-8c20d285d03e.png)

**Comment by orta** [comment]
Looking more like https://github.com/artsy/team-navigator/commit/a0cc52768b8d554f181ef282975e533e8238b88a - just went through those commits and clicked around, this is where I started getting them

**Comment by orta** [comment]
Resetting these three files back a stops it: 

```
 ~/d/p/a/j/s/team-navigator  ➦ a0cc527 ~$  git s                                                                                                       Mon 21 Aug 17:21:53 2017
HEAD detached at a0cc527
Changes to be committed:
  (use "git reset HEAD <file>..." to unstage)

	modified:   app/controllers/index.js
	modified:   app/router.js
	modified:   app/views/sidebar/locations-teams.js
```

**Comment by orta** [comment]
Stumped, ran out of time.

**Comment by orta** [comment]
Fixed 👍
