### ISSUE TITLE
Missing text on /did-you-know

### ISSUE THREAD

**Issue by bhoggard** [artsy/team-navigator#102]
It just cuts off:

Audio Pronounciations
Find out how to pronounce someone's name from themselves. We have recorded

Also, it should be "Pronunciations".

**Comment by orta** [comment]
Ah - that's what @dblock meant. So I think it can be finished off with "We have recorded voice clips of people at Artsy which you can find on people's profile pages.

**Comment by orta** [comment]
Fixed by #103
