### ISSUE TITLE
[Idea] Show a person’s local time.

### ISSUE THREAD

**Issue by alloy** [artsy/team-navigator#48]
For remote purposes, it would be great if we can easily find the local time of people on the team.
- Basically something like http://timezone.io, but without the need for everybody to sign-up for yet another external service.
- I think it should be displayed on the global overview page, so I can, for instance, filter by ‘iOS’ and in one glance see the local times of all my team members.
- I’d also like the time zone info to be retrieved from Gravity, so that when we, in the future, always update a user’s TZ info on app launch from Eigen, this would automatically get updated. https://github.com/artsy/eigen/issues/1043

NOTE: I’m open to building this myself.

**Comment by orta** [comment]
This is available inside the Slack API - https://gist.github.com/kasparsd/f8f36794ecf558915d6f

And so we could add a "is active" and "timezone" to a profile

**Comment by orta** [comment]
We now have up-to-date slack activity details - should be trivial to add the timezone metadata into our db. 

Form there it's just building that page.

**Comment by alloy** [comment]
Implemented in #83
