### ISSUE TITLE
Update ReadMe

### ISSUE THREAD

**Issue by berndpl** [artsy/team-navigator#54]
- What is the team navigator?
- Which problem does it solve?
- How does it look like in action?

I am just curious :)

**Comment by ashfurrow** [comment]
Good question, I'll tackle this at the same time as #53 (might not be this week, on vacation).

**Comment by orta** [comment]
Lols, I've just fixed this with v2 - thanks for the issue @berndpl - I didn't think adding images. Check the repo README.
