### ISSUE TITLE
New Design

### ISSUE THREAD

**Issue by craigspaeth** [artsy/team-navigator#57]
![full-2](https://cloud.githubusercontent.com/assets/555859/18484915/826a3d02-79b8-11e6-8ebd-96b7de973587.jpeg)

**Comment by OLI9292** [comment]
Would be cool if people had a different colored party hat on their birthday

**Comment by craigspaeth** [comment]
v1 Feature Set:

- [ ] Add role text
![image](https://cloud.githubusercontent.com/assets/555859/20944474/9d11c5fc-bbd1-11e6-95f2-510c82d5e4f1.png)

- [ ] Add links to email + calendar
![image](https://cloud.githubusercontent.com/assets/555859/20944519/cb145bf4-bbd1-11e6-874d-68ad81530d41.png)

- [ ] Add "Started x years ago" under role text maybe

- [ ] Add team information sidebar
![image](https://cloud.githubusercontent.com/assets/555859/20944568/fb3972ec-bbd1-11e6-8e02-13702afe4caa.png)

- [ ] Auth?

- [ ] Showing reporting structure in the typical tree/org-like way when filtering down by Team. e.g. Robert would be in the "Product" team, then Jesse in "Performance Marketing", Christine in "Organic Growth", and Nicolette in "Organic Growth". Then we would use `reports_to` to build up the tree, clicking on "Product would show the relationships all the way down, clicking on "Organic Growth" would just show Christine and her reports.

- [ ] Filtering in Product Team, sub-team, or practice (whatever is MVP) just orders by A–Z

**Comment by craigspaeth** [comment]
@orta Let's break this up into three big efforts

1. Tombstone info
2. Filter teams by the `team` field and deduce sub-teams + reporting structure from `reports_to`
3. Cleanup and deployment
