### ISSUE TITLE
Some team names and teamIDs out of sync

### ISSUE THREAD

**Issue by anandaroop** [artsy/team-navigator#72]
This is arguably a data issue that could be fixed in either the data source or in [this line that enumerates teams](https://github.com/artsy/team-navigator/blob/b902f65bfc98f1fe02ba3850057692ae532726bf/app/views/sidebar/locations-teams.js#L26) for the sidebar nav…

But currently:
- following the sidebar nav item **Partner Success & Revenue** leads to a blank page at https://team.artsy.net/team/partner-success-revenue 
- whereas changing the URL to https://team.artsy.net/team/partner-success (to match the data source) gives you the expected results 
- exact same issue for **Collector Experience & GMV** at https://team.artsy.net/team/collector-experience-gmv vs. https://team.artsy.net/team/collector-experience

**Comment by orta** [comment]
the "db" (spreadsheet) changed last night, meaning my special casings didn't exist anymore. ;)

All of this stuff should be fixed when I hit sync again

**Comment by orta** [comment]
Fixed!
