### ISSUE TITLE
Current time of team members is incorrect.

### ISSUE THREAD

**Issue by alloy** [artsy/team-navigator#85]
As you can see in the status bar, the actual local time in Amsterdam, at the time of loading the page, was 12:49, whereas the page says that it’s 10:49 in the CENTRAL EUROPEAN SUMMER TIME timezone. It also isn’t PM in New York right now, it’s very early AM.

<img width="519" alt="screen shot 2017-03-29 at 12 51 14" src="https://cloud.githubusercontent.com/assets/2320/24451291/7eaac25c-147e-11e7-90b6-0b40e441af03.png">

**Comment by orta** [comment]
I bet this is due to the server timezones, we're given an "offset" from slack, so finding out where 0 is should be enough

**Comment by orta** [comment]
I'll try get my GMT one right, then see if everything else sorts itself :D

**Comment by orta** [comment]
Fixed with https://github.com/artsy/team-navigator/commit/b5602fc91951f0736de6ef9bf6ee850105d81e7f
